version: '3.8'
networks:
  replica:
    driver: bridge
    
services:
  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - 6379:6379
    networks:
      - replica
#    volumes:
#      - ./conf/redis-master.conf:/usr/local/etc/redis/
    restart: always

  replica:
    container_name: replica
    image: redis:6.2
    ports:
      - 6380:6379
    networks:
      - replica
    volumes:
      - ./conf:/usr/local/etc/redis/
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  redis-sentinel:
    container_name: redis-sentinel
    image: redis:6.2
    ports:
      - 26379:26379
    volumes:
      - ./conf/sentinel.conf:/usr/local/etc/redis/
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
